import { completeConfigBase } from "eslint-config-complete";
import { defineConfig } from "eslint/config";

export default defineConfig(
  ...completeConfigBase,

  {
    ignores: [
      ".build/**",
      ".playwright-cli/**",
      "dist/**",
      "fixtures/ccxp-snapshot/**",
      "node_modules/**",
      "src/content.decaptcha.model.ts",
    ],
  },

  {
    files: ["**/*.d.ts"],
    rules: {
      "import-x/no-default-export": "off",
    },
  },

  {
    rules: {
      "@stylistic/quotes": "off",
      "@typescript-eslint/consistent-type-definitions": "off",

      "@typescript-eslint/no-unsafe-argument": "off",
      "@typescript-eslint/no-unsafe-assignment": "off",
      "@typescript-eslint/no-unsafe-call": "off",
      "@typescript-eslint/no-unsafe-member-access": "off",
      "@typescript-eslint/no-unsafe-return": "off",
      "@typescript-eslint/no-unnecessary-boolean-literal-compare": "off",
      "@typescript-eslint/no-unnecessary-condition": "off",
      "@typescript-eslint/no-useless-default-assignment": "off",
      "@typescript-eslint/prefer-destructuring": "off",
      "@typescript-eslint/prefer-nullish-coalescing": "off",
      "@typescript-eslint/promise-function-async": "off",
      "@typescript-eslint/restrict-plus-operands": "off",
      "@typescript-eslint/strict-boolean-expressions": "off",
      "@typescript-eslint/strict-void-return": "off",
      "complete/complete-sentences-line-comments": "off",
      "complete/format-line-comments": "off",
      "complete/no-let-any": "off",
      "complete/no-mutable-return": "off",
      "complete/no-object-any": "off",
      "complete/no-string-length-0": "off",
      "complete/no-unnecessary-assignment": "off",
      "complete/prefer-is-array": "off",
      "complete/prefer-plusplus": "off",
      "complete/prefer-readonly-parameter-types": "off",
      "complete/require-ascii": "off",
      "complete/require-capital-const-assertions": "off",
      "complete/require-capital-read-only": "off",
      "complete/require-variadic-function-argument": "off",
      "complete/strict-array-methods": "off",
      "import-x/no-default-export": "off",
      "import-x/no-commonjs": "off",
      "import-x/no-unassigned-import": [
        "error",
        {
          allow: ["**/*.css"],
        },
      ],
      "jsdoc/reject-any-type": "off",
      "jsdoc/type-formatting": "off",
      "n/file-extension-in-import": "off",
      "n/no-callback-literal": "off",
      "no-bitwise": "off",
      "no-nested-ternary": "off",
      "no-param-reassign": "off",
      "no-void": "off",
      "perfectionist/sort-array-includes": "off",
      "unicorn/better-regex": "off",
      "unicorn/catch-error-name": "off",
      "unicorn/consistent-existence-index-check": "off",
      "unicorn/consistent-function-scoping": "off",
      "unicorn/escape-case": "off",
      "unicorn/import-style": "off",
      "unicorn/no-array-for-each": "off",
      "unicorn/no-array-reduce": "off",
      "unicorn/no-array-sort": "off",
      "unicorn/no-negated-condition": "off",
      "unicorn/no-null": "off",
      "unicorn/numeric-separators-style": "off",
      "unicorn/prefer-at": "off",
      "unicorn/prefer-add-event-listener": "off",
      "unicorn/prefer-array-find": "off",
      "unicorn/prefer-dom-node-append": "off",
      "unicorn/prefer-dom-node-dataset": "off",
      "unicorn/prefer-dom-node-remove": "off",
      "unicorn/prefer-import-meta-properties": "off",
      "unicorn/prefer-math-min-max": "off",
      "unicorn/prefer-modern-dom-apis": "off",
      "unicorn/prefer-number-properties": "off",
      "unicorn/prefer-query-selector": "off",
      "unicorn/prefer-spread": "off",
      "unicorn/prefer-string-raw": "off",
      "unicorn/prefer-string-replace-all": "off",
      "unicorn/prefer-switch": "off",
      "unicorn/prefer-type-error": "off",
      "unicorn/require-module-specifiers": "off",
    },
  },
);
