(function registerCcxpLiteSharedConstants(globalScope: typeof globalThis) {
  const runtimeScope = globalScope;
  runtimeScope.CCXP_LITE ??= {};
  const namespace = runtimeScope.CCXP_LITE;

  const TOKENS = {
    colorPrimary: "rgb(121, 36, 133)",
    colorAccent: "#d5dbe1",
    colorBrand: "rgb(121, 36, 133)",
    colorLegacyBlueText: "#2e4978",
    colorLegacyRedText: "#b85c68",
    colorBg: "#ffffff",
    colorSurface: "#ffffff",
    colorSidebarSurface: "#f5f7f9",
    colorSurfaceMuted: "#f5f7f9",
    colorBorder: "rgba(31, 41, 51, 0.12)",
    colorSidebarDivider: "rgba(31, 41, 51, 0.16)",
    colorSidebarSearchSurface: "rgba(255, 255, 255, 0.9)",
    colorSidebarSearchGradientStart: "rgba(255, 255, 255, 0.98)",
    colorSidebarSearchBorder: "rgba(31, 41, 51, 0.1)",
    colorPrimaryFocusBorder: "rgba(121, 36, 133, 0.28)",
    colorPrimaryFocusRing: "rgba(121, 36, 133, 0.08)",
    colorPrimaryHoverSurface: "rgba(124, 45, 146, 0.06)",
    colorPrimaryMutedSurface: "rgba(124, 45, 146, 0.04)",
    colorPrimaryGlow: "rgba(121, 36, 133, 0.18)",
    colorSidebarSearchPlaceholder: "#6b7280",
    colorText: "#111827",
    colorTextMuted: "#52606d",
    colorTransparent: "transparent",
    colorSkeletonSurfaceEndTint: "#eef2f6",
    colorSkeletonHighlightStart: "rgba(255, 255, 255, 0)",
    colorSkeletonHighlightSoft: "rgba(255, 255, 255, 0.3)",
    colorSkeletonHighlightStrong: "rgba(255, 255, 255, 0.88)",
    spacingXs: "6px",
    spacingSm: "10px",
    spacingMd: "16px",
    spacingLg: "24px",
    spacingXl: "32px",
    spacing2xs: "4px",
    spacing3xs: "2px",
    spacingInlineSm: "8px",
    spacingInsetSm: "12px",
    spacingInsetMd: "14px",
    spacingInsetLg: "18px",
    spacingBrandInline: "12px",
    spacingSidebarSearchInset: "12px",
    sidebarRowPaddingY: "12px",
    sidebarRowPaddingX: "10px",
    sidebarRowGap: "6px",
    sidebarTreeIndentStep: "1em",
    radiusSm: "10px",
    radiusMd: "14px",
    radiusLg: "20px",
    radiusXs: "6px",
    radiusInput: "8px",
    radiusBrand: "12px",
    radiusFull: "999px",
    fontSans: '"Noto Sans TC", "PingFang TC", "Microsoft JhengHei", sans-serif',
    fontBrand: '"Futura", "Futura PT", "Avenir Next", sans-serif',
    fontWeightRegular: "400",
    fontWeightStrong: "700",
    fontWeightHeavy: "800",
    fontVariantNumericTabular: "tabular-nums",
    fontSizeCaption: "14px",
    fontSizeNav: "14px",
    fontSizeUtility: "14px",
    fontSizeBody: "16px",
    fontSizeSidebarBrand: "20px",
    sizeSidebarBrandLogo: "30px",
    sizeSidebarCategoryLeading: "1.5em",
    sizeSidebarControl: "24px",
    sizeSidebarGuideLine: "2px",
    sizeSidebarSearchSpacer: "14px",
    sizeSidebarSearchWidth: "268px",
    spacingSidebarBrandWordGap: "0.5ch",
    sizeSidebarHeaderDividerWidth: "100%",
    sizeSidebarHeaderDividerHeight: "1px",
    sizeSidebarSearchIcon: "20px",
    sizeLandingBrandLogo: "32px",
    sizeLandingHeaderHeight: "68px",
    sizeFormControlWidth: "320px",
    sizeLoginControlHeight: "48px",
    sizePasswordToggleOffset: "44px",
    sizeIconButtonSm: "24px",
    sizeIconButtonMd: "36px",
    sizeSidebarSectionIcon: "42px",
    sizeSidebarCategoryCardIcon: "48px",
    sizeControlMinWidth: "112px",
    sizeControlHeightSm: "38px",
    sizeControlHeightMd: "44px",
    sizeSidebarSectionCardMinHeight: "72px",
    sizeSidebarCategoryCardMinHeight: "72px",
    sizeSidebarDestinationFrameOffset: "276px",
    sizeAnnouncementDivider: "18px",
    fontSizePageTitle: "26px",
    fontSizeDisplay: "30px",
    fontSizeSectionTitle: "18px",
    fontSizeChip: "13px",
    landingMaxWidth: "960px",
    sidebarWidth: "324px",
    sidebarClass: "ccxp-lite-sidebar-shell",
    mainClass: "ccxp-lite-main-skin",
    landingClass: "ccxp-lite-landing-shell",
  } as const;

  const LOCALIZED_STRINGS = {
    en: {
      sidebarTitle: "NTHU AIS",
      landingTitle: "NTHU AIS Login",
      loginTitle: "Login",
      emptyGroup: "No items available in this section",
      servicePhone: "Service Phone",
      cannotLogin: "Can't log in?",
      externalLinksLabel: "External links",
      portalSectionsLabel: "Portal sections",
      sidebarSearchPlaceholder: "Search menu",
      sidebarSearchNoResults: "No matching items",
      sidebarCategoryFavorites: "Favorite",
      sidebarFavoritesEmpty: "Press star at any function to save it here",
      sidebarAddFavorite: "Add to favorites",
      sidebarRemoveFavorite: "Remove from favorites",
      announcementDate: "Date",
      announcementTopic: "Topic",
      playVerificationAudio: "Play verification audio",
      showPassword: "Show password",
      hidePassword: "Hide password",
      fieldAccount: "Account",
      fieldPassword: "Password",
      fieldVerificationCode: "Verification Code",
      fieldStudentId: "Student ID",
      fieldGeneric: "Field",
      sidebarCategoryProfile: "Personal Info",
      sidebarCategoryPlanningAndEnrollment: "Planning & Enrollment",
      sidebarCategoryCoursesAndGrades: "Courses & Grades",
      sidebarCategoryTeachingFeedback: "Teaching Feedback",
      sidebarCategoryStatusChanges: "Status Changes",
      sidebarCategoryGraduationAndDefense: "Graduation & Defense",
      sidebarCategoryPaymentsAndAid: "Payments & Aid",
      sidebarCategoryFinancialAid: "Aid & Tuition Relief",
      sidebarCategoryHousingAndLife: "Housing & Life",
      sidebarCategoryForms: "Forms",
      sidebarCategoryCampusSystems: "Campus Systems",
      sidebarCategoryAnnouncementsAndVoting: "Notices & Voting",
      sidebarCategoryOtherSection: "Other",
      sidebarPinned: "Pinned",
      sidebarPinnedAlt: "Pinned items",
      sidebarAll: "All",
      sidebarAllAlt: "All functions",
      sidebarBack: "Back",
      sidebarOpenCategory: "Open category",
      sidebarResetHome: "Go to home",
      sidebarGitHubLink: "ccxpLite",
      sidebarBrandPartner: "ccxp",
      sidebarFavoritesEmptyTitle: "No pinned items yet",
      sidebarFavoritesEmptyBody: "Star any function card to keep it here for quick access.",
      sidebarRemovePinnedDialogTitlePrefix: "Remove ",
      sidebarRemovePinnedDialogTitleSuffix: "?",
      sidebarRemovePinnedDialogDescription: "this item will no longer be quick-accessible",
      sidebarRemovePinnedDialogCancel: "Keep it",
      sidebarRemovePinnedDialogConfirm: "Confirm",
      sidebarSearchEmptyTitle: "No matching items",
      sidebarSearchEmptyBody: "Try another keyword or go back to browse categories.",
      sidebarSectionEmptyTitle: "Nothing to show here",
      sidebarSectionEmptyBody: "This section currently has no available items.",
      sidebarDestinationLoading: "Loading page",
      sidebarDestinationErrorTitle: "Page failed to load",
      sidebarDestinationErrorBody: "Try reloading this page or open it in a new tab.",
      sidebarRetry: "Retry",
      sidebarOpenInNewTab: "Open in new tab",
      sidebarExperimentLabel: "Lab",
      sidebarExperimentCaption: "Experimental",
      sidebarVariantClassic: "Classic",
      sidebarVariantLayered: "Layered",
      sidebarSwitchToClassic: "Switch to classic sidebar",
      sidebarSwitchToLayered: "Switch to layered menu",
    },
    zh: {
      sidebarTitle: "校務資訊系統",
      landingTitle: "校務資訊系統登入",
      loginTitle: "登入",
      emptyGroup: "此分類暫無可顯示項目",
      servicePhone: "服務電話",
      cannotLogin: "無法登入",
      externalLinksLabel: "外部連結",
      portalSectionsLabel: "入口分區",
      sidebarSearchPlaceholder: "搜尋功能",
      sidebarSearchNoResults: "找不到符合項目",
      sidebarCategoryFavorites: "常用功能",
      sidebarFavoritesEmpty: "按下任意功能旁的星號以儲存",
      sidebarAddFavorite: "加入常用功能",
      sidebarRemoveFavorite: "移除常用功能",
      announcementDate: "日期",
      announcementTopic: "新聞主題",
      playVerificationAudio: "播放驗證碼語音",
      showPassword: "顯示密碼",
      hidePassword: "隱藏密碼",
      fieldAccount: "帳號",
      fieldPassword: "密碼",
      fieldVerificationCode: "驗證碼",
      fieldStudentId: "學號",
      fieldGeneric: "欄位",
      sidebarCategoryProfile: "個人資料",
      sidebarCategoryPlanningAndEnrollment: "預排與選課",
      sidebarCategoryCoursesAndGrades: "課程成績",
      sidebarCategoryTeachingFeedback: "教學意見",
      sidebarCategoryStatusChanges: "學籍異動",
      sidebarCategoryGraduationAndDefense: "畢業與口試",
      sidebarCategoryPaymentsAndAid: "繳費與補助",
      sidebarCategoryFinancialAid: "助學與減免",
      sidebarCategoryHousingAndLife: "住宿與生活",
      sidebarCategoryForms: "表單系統",
      sidebarCategoryCampusSystems: "校園系統",
      sidebarCategoryAnnouncementsAndVoting: "公告與投票",
      sidebarCategoryOtherSection: "其他",
      sidebarPinned: "已釘選",
      sidebarPinnedAlt: "已釘選功能",
      sidebarAll: "所有功能",
      sidebarAllAlt: "所有功能",
      sidebarBack: "返回",
      sidebarOpenCategory: "查看分類",
      sidebarResetHome: "回到首頁",
      sidebarGitHubLink: "ccxpLite",
      sidebarBrandPartner: "ccxp",
      sidebarFavoritesEmptyTitle: "尚未釘選功能",
      sidebarFavoritesEmptyBody: "在任一功能卡按下星號，即可將它固定在這裡。",
      sidebarRemovePinnedDialogTitlePrefix: "移除「",
      sidebarRemovePinnedDialogTitleSuffix: "」？",
      sidebarRemovePinnedDialogDescription: "這個項目將不再顯示於快速存取。",
      sidebarRemovePinnedDialogCancel: "保留",
      sidebarRemovePinnedDialogConfirm: "確認移除",
      sidebarSearchEmptyTitle: "找不到符合項目",
      sidebarSearchEmptyBody: "試試其他關鍵字，或返回上一層瀏覽分類。",
      sidebarSectionEmptyTitle: "目前沒有可顯示內容",
      sidebarSectionEmptyBody: "這個區塊目前沒有可用項目。",
      sidebarDestinationLoading: "頁面載入中",
      sidebarDestinationErrorTitle: "頁面載入失敗",
      sidebarDestinationErrorBody: "可以重新嘗試載入，或改用新分頁開啟。",
      sidebarRetry: "重試",
      sidebarOpenInNewTab: "新分頁開啟",
      sidebarExperimentLabel: "Lab",
      sidebarExperimentCaption: "實驗性功能",
      sidebarVariantClassic: "經典側欄",
      sidebarVariantLayered: "分層選單",
      sidebarSwitchToClassic: "切換為經典側欄",
      sidebarSwitchToLayered: "切換為分層選單",
    },
  } as const;

  const SIDEBAR_CATEGORIES = [
    {
      id: "profile",
      labelKey: "sidebarCategoryProfile",
      fallbackLabel: "個人資料",
      icon: "circle-user-round",
      itemLabels: ["帳號相關維護", "個人資料維護", "導師聯繫資料", "原住民資料系統"],
      summaryLabels: ["帳號", "個資", "導師", "原住民"],
    },
    {
      id: "planning-and-enrollment",
      labelKey: "sidebarCategoryPlanningAndEnrollment",
      fallbackLabel: "預排與選課",
      icon: "calendar-range",
      itemLabels: [
        "預排系統 Tentative schedule",
        "選課 Select courses",
        "校際/跨系統選修",
        "暑修 Summer courses",
      ],
      summaryLabels: ["預排", "選課", "跨系", "暑修"],
    },
    {
      id: "courses-and-grades",
      labelKey: "sidebarCategoryCoursesAndGrades",
      fallbackLabel: "課程成績",
      icon: "notepad-text",
      itemLabels: ["課程、成績 Courses, transcript", "學分&抵免學分"],
      summaryLabels: ["課程", "成績", "學分", "抵免"],
    },
    {
      id: "teaching-feedback",
      labelKey: "sidebarCategoryTeachingFeedback",
      fallbackLabel: "教學意見",
      icon: "message-square-more",
      itemLabels: ["教學意見 Comments about courses", "傑出教學教師票選", "教學助理評量問卷"],
      summaryLabels: ["課評", "票選", "助教", "問卷"],
    },
    {
      id: "status-changes",
      labelKey: "sidebarCategoryStatusChanges",
      fallbackLabel: "學籍異動",
      icon: "refresh-cw",
      itemLabels: ["申請復學", "保留生申請入學", "轉系所申請", "兵役業務"],
      summaryLabels: ["復學", "保留", "轉系", "兵役"],
    },
    {
      id: "graduation-and-defense",
      labelKey: "sidebarCategoryGraduationAndDefense",
      fallbackLabel: "畢業與口試",
      icon: "graduation-cap",
      itemLabels: ["畢業審查", "研究生學位考試", "畢業生離校系統", "數位學位證書", "袍服借用申請"],
      summaryLabels: ["審查", "口試", "離校", "學位證"],
    },
    {
      id: "payments-and-aid",
      labelKey: "sidebarCategoryPaymentsAndAid",
      fallbackLabel: "繳費與補助",
      icon: "dollar-sign",
      itemLabels: [
        "繳費單相關作業(出納組)",
        "退費查詢",
        "所得相關查詢",
        "出納傳票付款查詢",
        "國外差旅費",
      ],
      summaryLabels: ["繳費", "退費", "所得", "傳票"],
    },
    {
      id: "financial-aid",
      labelKey: "sidebarCategoryFinancialAid",
      fallbackLabel: "助學與減免",
      icon: "hand-coins",
      itemLabels: ["就學貸款", "弱勢助學作業", "學雜費減免作業"],
      summaryLabels: ["貸款", "弱勢助學", "學雜費減免"],
    },
    {
      id: "housing-and-life",
      labelKey: "sidebarCategoryHousingAndLife",
      fallbackLabel: "住宿與生活",
      icon: "house",
      itemLabels: ["外宿資料", "學生宿舍相關", "健康照護系統", "職涯諮詢與評測"],
      summaryLabels: ["外宿", "宿舍", "健康", "職涯"],
    },
    {
      id: "forms",
      labelKey: "sidebarCategoryForms",
      fallbackLabel: "表單系統",
      icon: "notebook-pen",
      itemLabels: [
        "學生請假系統",
        "電子表單系統",
        "計畫差勤及臨時工時登錄系統",
        "出國申請與報告繳交系統",
        "校外實習登錄平台",
      ],
      summaryLabels: ["請假", "表單", "差勤", "出國"],
    },
    {
      id: "campus-systems",
      labelKey: "sidebarCategoryCampusSystems",
      fallbackLabel: "校園系統",
      icon: "school",
      itemLabels: ["學習平台", "計通中心相關服務", "研發處資訊系統", "校內其他系統", "明燈平台"],
      summaryLabels: ["學習", "計通", "研發", "校內"],
    },
    {
      id: "announcements-and-voting",
      labelKey: "sidebarCategoryAnnouncementsAndVoting",
      fallbackLabel: "公告與投票",
      icon: "megaphone",
      itemLabels: [
        "會議紀錄",
        "校內業務公告",
        "線上投票系統",
        "線上投票系統(特殊投票)",
        "校園通報網",
      ],
      summaryLabels: ["會議", "公告", "投票", "通報"],
    },
  ] as const;

  const ASSETS = {
    brandLogoPath: "assets/nthu.jpg",
    sidebarBrandLogoPath: "assets/nthu.png",
    stylesheetPath: "content.css",
  } as const;

  namespace.sharedConstants = {
    TOKENS,
    LOCALIZED_STRINGS,
    SIDEBAR_CATEGORIES,
    ASSETS,
  };
})(globalThis);
